version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            target: prerelase
        ports:
            - 8000:3000
        network_mode: host
