import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Title } from "@/component/Title";
import { Footer } from "@/component/Footer";
import { Action } from "@/component/Action";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Locker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Title />
        {children}
        <Action />
        <Footer />
      </body>
    </html>
  );
}
